Repository Nomifactory/Nomifactory, pull requests merged in 2020-04, with the labels that each got.

#399 Setup Travis CI for automated pack building
  .gitignore
  .travis.sh
  .travis.yml
  buildtools/.eslintrc.js
  buildtools/.gitignore
  buildtools/config.default.js
  buildtools/globals.js
  buildtools/gulpfile.js
  buildtools/package-lock.json
  buildtools/package.json
  buildtools/tasks/client/index.js
  buildtools/tasks/server/index.js
  buildtools/tasks/travis/checks.js
  buildtools/tasks/travis/index.js
  buildtools/util/downloaders.js
  buildtools/util/hashes.js
  buildtools/util/util.js
  launchscripts/launch.bat
  launchscripts/launch.sh
  modlist.html
  serverfiles/server.properties
Labels: Auto-Build

#346 New recipes for lots of AR blocks
  overrides/scripts/AdvRocketry.zs
Labels: 1.3 mod updates

#398 Safe mod updates 2
  manifest.json
  overrides/config/cofh/core/client.cfg
  overrides/config/cofh/core/common.cfg
  overrides/config/cofh/redstonearsenal/client.cfg
  overrides/config/cofh/redstonearsenal/common.cfg
  overrides/config/cofh/thermalcultivation/client.cfg
  overrides/config/cofh/thermalcultivation/common.cfg
  overrides/config/cofh/thermalexpansion/client.cfg
  overrides/config/cofh/thermalexpansion/common.cfg
  overrides/config/cofh/thermalexpansion/florbs.cfg
  overrides/config/cofh/thermalexpansion/morbs.cfg
  overrides/config/cofh/thermalfoundation/client.cfg
  overrides/config/cofh/thermalfoundation/common.cfg
  overrides/config/cofh/thermalinnovation/client.cfg
  overrides/config/cofh/thermalinnovation/common.cfg
  overrides/config/cofh/world/config.cfg
  overrides/config/jei/itemBlacklist.cfg
  overrides/config/jei/jei.cfg
  overrides/config/jei/searchColors.cfg
  overrides/config/journeymap_ModInfo.cfg
  overrides/config/journeymap_server.cfg
  overrides/config/nuclearcraft.cfg
Labels: enhancement

#323 Greggify Advanced Rocketry recipes
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#408 NC Cleanup Effort
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/JEICleanup.zs
  overrides/scripts/Nuclearcraft.zs
  overrides/scripts/ThermalExpansion.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#400 Add Sponge Recipe
  overrides/scripts/Earlygame.zs
Labels: enhancement

#392 Add Infinity Grain Block as Microminer output
  overrides/scripts/Microverse.zs
Labels: enhancement

#348 Oil Rig Rebalance
  overrides/scripts/Microverse.zs
Labels: enhancement

#420 Microverse refactor
  overrides/scripts/CommonVars.zs
  overrides/scripts/Microverse.zs
Labels: enhancement
