Repository Nomifactory/Nomifactory, pull requests merged in 2020-07, with the labels that each got.

#541 Fix wrong info in questbook for mob simulator.
  overrides/config/betterquesting/DefaultQuests.json
Labels: enhancement, questbook

#522 Make certain ContentTweaker additions more in-line with what they represent.
  overrides/resources/contenttweaker/blockstates/block_dust.json
  overrides/resources/contenttweaker/blockstates/denseoilshale.json
  overrides/resources/contenttweaker/blockstates/excitationcoil.json
  overrides/resources/contenttweaker/blockstates/moltenempoweredvoid.json
  overrides/resources/contenttweaker/lang/en_us.lang
  overrides/resources/contenttweaker/models/block/denseoilshale.json
  overrides/resources/contenttweaker/models/block/excitationcoil.json
  overrides/resources/contenttweaker/models/item/block_dust.json
  overrides/resources/contenttweaker/models/item/denseoilshale.json
  overrides/resources/contenttweaker/models/item/excitationcoil.json
  overrides/resources/contenttweaker/textures/blocks/block_dust.png
  overrides/resources/contenttweaker/textures/blocks/denseoilshaleeast.png
  overrides/resources/contenttweaker/textures/blocks/denseoilshalenorth.png
  overrides/resources/contenttweaker/textures/blocks/denseoilshaleup.png
  overrides/resources/contenttweaker/textures/items/block_dust.png
  overrides/resources/contenttweaker/textures/items/denseoilshale.png
  overrides/resources/contenttweaker/textures/items/excitationcoil.png
  overrides/scripts/ContentTweaker.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/PortedMaterials.zs
  overrides/scripts/ThermalExpansion.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#543 Add Nether Star Nuggets to Compacting Drawers
  overrides/config/storagedrawers.cfg
  overrides/scripts/ExtendedCrafting.zs
Labels: enhancement

#551 Fix Pure Crystals in Phytogenic Insolator.
  overrides/scripts/ThermalExpansion.zs
Labels: bug

#520 S'mores and More S'mores
  overrides/resources/contenttweaker/lang/en_us.lang
  overrides/resources/contenttweaker/models/item/eightsmore.json
  overrides/resources/contenttweaker/models/item/sixteensmore.json
  overrides/resources/contenttweaker/models/item/sixtyfoursmore.json
  overrides/resources/contenttweaker/models/item/thirtytwosmore.json
  overrides/resources/contenttweaker/textures/items/eightsmore.png
  overrides/resources/contenttweaker/textures/items/sixteensmore.png
  overrides/resources/contenttweaker/textures/items/sixtyfoursmore.png
  overrides/resources/contenttweaker/textures/items/thirtytwosmore.png
  overrides/scripts/ContentTweaker.zs
  overrides/scripts/Nuclearcraft.zs
Labels: enhancement
