Repository Nomifactory/Nomifactory, pull requests merged in 2020-10, with the labels that each got.

#622 Adjust the prerequisites of the SMP quest
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook

#621 Refactor brewery recipes
  overrides/scripts/Midgame.zs
Labels: bug, enhancement

#566 Update Armor Plus
  manifest.json
  overrides/config/armorplus/dimensions.cfg
  overrides/scripts/_oreDict.zs
Labels: enhancement

#605 Add GT recipes for Solidified Experience
  overrides/scripts/Microverse.zs
Labels: enhancement

#574 Unify Draconium Recipes to the Draconic Evolution variant
  overrides/scripts/DraconicEvolution.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#528 Remove Filled Fluid Containers from JEI
  overrides/scripts/JEICleanup.zs
Labels: enhancement

#624 AE2 adjustments
  overrides/scripts/ModSpecific/AppliedEnergistics2.zs
Labels: AE2, enhancement

#620 Allow for all of the chisel space blocks in Microverse Projectors.
  overrides/config/betterquesting/DefaultQuests.json
  overrides/scripts/Multiblocks.zs
Labels: enhancement
