Repository Nomifactory/Nomifactory, pull requests merged in 2020-01, with the labels that each got.

#284 Change the amount of Molten Tank produced by a Heart
  overrides/scripts/ExtendedCrafting.zs
Labels: enhancement

#303 Replace PackagedAvaritia with PackagedExCrafting
  manifest.json
  modlist.html
  overrides/config/AppliedEnergistics2/items.csv
  overrides/scripts/AdvRocketry.zs
Labels: enhancement

#292 Should fix MM casings being craftable by hand
  overrides/scripts/Endgame.zs
  overrides/scripts/Microverse.zs
Labels: enhancement

#290 Allow GTCE aluminum to be chiselable
  overrides/scripts/_oreDict.zs
Labels: enhancement

#306 Update EnderIO and related mods
  manifest.json
  overrides/scripts/EnderIO.zs
  overrides/scripts/_oreDict.zs
Labels: 1.3 mod updates

#286 Add dirt recipe
  overrides/scripts/Earlygame.zs
  overrides/scripts/SolarFlux.zs
Labels: enhancement

#287 Add additional Enderio Glasses
  overrides/scripts/EnderIO.zs
Labels: enhancement

#311 Remove ZPMs from the jungle temple loot table
  manifest.json
  modlist.html
  overrides/config/loottweaker.cfg
  overrides/scripts/LootTweaker.zs
Labels: enhancement

#313 Unhide Micro Miner Cores/Frames and remove TE Sawdust
  overrides/scripts/Earlygame.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/JetpacksAndEnergyStorage.zs
  overrides/scripts/_oreDict.zs
Labels: bug
