Repository Nomifactory/Nomifactory, pull requests merged in 2020-08, with the labels that each got.

#578 Use material id 976 for microversium (fixes #570 and reverts 31c642b)
  overrides/scripts/JEICleanup.zs
  overrides/scripts/PortedMaterials.zs
  overrides/scripts/_oreDict.zs
Labels: bug

#577 Fix the Smashing Enchant giving regular Dilithium Crystals
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/Multiblocks.zs
  overrides/scripts/_oreDict.zs
Labels: bug

#573 Modify the Late Game quest Tab for clearer progression
  overrides/config/betterquesting/DefaultQuests.json
  overrides/scripts/_oreDict.zs
Labels: questbook

#591 Safe Mod Updates 3
  manifest.json
  overrides/config/LogisticsPipes.cfg
  overrides/config/advRocketry/advancedRocketry.cfg
  overrides/config/betterquesting.cfg
  overrides/config/bloodymods/actuallyaddon.cfg
  overrides/config/bloodymods/bloodylib.cfg
  overrides/config/cofh/redstonearsenal/client.cfg
  overrides/config/cofh/redstonearsenal/common.cfg
  overrides/config/enderio/enderio.cfg
  overrides/config/enderio/enderiomachines.cfg
  overrides/config/littletiles.cfg
  overrides/config/nuclearcraft.cfg
  overrides/config/randompatches.cfg
  overrides/config/storagedrawers.cfg
  overrides/config/xtones.cfg
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/EnderIO.zs
  overrides/scripts/LootTweaker.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#556 Add Phosphor
  manifest.json
  overrides/config/phosphor.json
Labels: enhancement

#588 Fix GTCE / NC Mess
  overrides/config/storagedrawers.cfg
  overrides/scripts/CommonVars.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/Endgame.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/Nuclearcraft.zs
  overrides/scripts/_oreDict.zs
  overrides/scripts/zzzFixStuff.zs
Labels: bug
