Repository Nomifactory/Nomifactory, pull requests merged in 2020-06, with the labels that each got.

#498 Disable MoreCauldrons wood burning
  overrides/config/morecauldrons.cfg
Labels: enhancement

#486 Add NC tiny clumps packager recipes
  overrides/scripts/CommonVars.zs
  overrides/scripts/Nuclearcraft.zs
Labels: enhancement

#502 Update theoneprobe.cfg
  overrides/config/theoneprobe.cfg
Labels: enhancement

#509 Register Moon Dust as dustMoon
  overrides/scripts/_oreDict.zs
Labels: enhancement

#499 Switch multiblocks to MBTweaker
  manifest.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/modularmachinery/machinery/cryogenicairdistillation.json
  overrides/config/modularmachinery/machinery/large_microverse.json
  overrides/config/modularmachinery/machinery/lunarminingstation.json
  overrides/config/modularmachinery/machinery/medium_microverse.json
  overrides/config/modularmachinery/machinery/naquadahreactormk1.json
  overrides/config/modularmachinery/machinery/naquadahreactormk2.json
  overrides/config/modularmachinery/machinery/oildrillingrig.json
  overrides/config/modularmachinery/machinery/small_microverse.json
  overrides/resources/contenttweaker/blockstates/microverse_casing.json
  overrides/resources/contenttweaker/blockstates/microverse_vent.json
  overrides/resources/contenttweaker/lang/en_us.lang
  overrides/resources/contenttweaker/models/block/microverse_casing.json
  overrides/resources/contenttweaker/models/block/microverse_vent.json
  overrides/resources/contenttweaker/models/item/microverse_casing.json
  overrides/resources/contenttweaker/models/item/microverse_vent.json
  overrides/resources/contenttweaker/textures/blocks/microverse_casing.png
  overrides/resources/contenttweaker/textures/blocks/microverse_vent.png
  overrides/resources/multiblocktweaker/lang/en_us.lang
  overrides/resources/multiblocktweaker/textures/gui/progress_bar/rocket.png
  overrides/resources/pack.mcmeta
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/ContentTweaker.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/JEICleanup.zs
  overrides/scripts/Microverse.zs
  overrides/scripts/Midgame.zs
  overrides/scripts/Multiblocks.zs
  overrides/scripts/PortedMaterials.zs
  overrides/scripts/SolarFlux.zs
  overrides/scripts/Textures.zs
  overrides/scripts/_oreDict.zs
Labels: Mod Addition Request, enhancement

#526 Add Random Patches, VanillaFix, and ReAuth
  manifest.json
  overrides/config/randompatches.cfg
Labels: Mod Addition Request, enhancement

#533 Add Dynamistics by Eutro
  manifest.json
Labels: Mod Addition Request

#531 Add Unique Recipes for multiblock controllers
  overrides/scripts/Multiblocks.zs
Labels: enhancement

#539 Modify Facade hiding so that one is visible
  overrides/scripts/JEICleanup.zs
Labels: enhancement
