Repository Nomifactory/Nomifactory, pull requests merged in 2020-03, with the labels that each got.

#272 Revamp the questbook
  overrides/config/betterquesting/DefaultQuests.json
  overrides/scripts/_oreDict.zs
Labels: questbook

#343 Add methods of obtaining black dye
  overrides/scripts/EnderIO.zs
  overrides/scripts/ThermalExpansion.zs
Labels: enhancement

#342 Make booster card infinite, adjust recipe
  overrides/config/AE2WirelessTerminals.cfg
  overrides/scripts/AE2.zs
Labels: enhancement

#294 Fix gaps in renewable resources with microminers
  overrides/config/betterquesting/DefaultQuests.json
  overrides/scripts/Microverse.zs
Labels: enhancement

#339 Change Ultimate boots recipe to not use Wyvern and Draconic boots.
  overrides/scripts/Armors.zs
Labels: bug

#360 Add Space Suit Upgrade Recipes
  overrides/scripts/AdvRocketry.zs
Labels: enhancement

#345 Unhide Pipe Sealer.
  overrides/scripts/_oreDict.zs
Labels: question

#304 Disable double ingots and curved plates
  overrides/config/gtadditions.cfg
  overrides/scripts/JEICleanup.zs
Labels: enhancement

#335 Unify Neutronium Plates
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/Endgame.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#375 Fix Validation error in #259
  overrides/scripts/ExtendedCrafting.zs
Labels: bug

#378 Add gtce Ore Gen to lost cities Dimension
  overrides/config/gregtech/worldgen/overworld/apatite_vein.json
  overrides/config/gregtech/worldgen/overworld/bauxite_vein.json
  overrides/config/gregtech/worldgen/overworld/beryllium_vein.json
  overrides/config/gregtech/worldgen/overworld/coal_vein.json
  overrides/config/gregtech/worldgen/overworld/copper_vein.json
  overrides/config/gregtech/worldgen/overworld/diamond_vein.json
  overrides/config/gregtech/worldgen/overworld/galena_vein.json
  overrides/config/gregtech/worldgen/overworld/heavy_oil_sphere.json
  overrides/config/gregtech/worldgen/overworld/iron_vein.json
  overrides/config/gregtech/worldgen/overworld/lapis_vein.json
  overrides/config/gregtech/worldgen/overworld/light_oil_sphere.json
  overrides/config/gregtech/worldgen/overworld/lignitecoal_vein.json
  overrides/config/gregtech/worldgen/overworld/magnetite_vein.json
  overrides/config/gregtech/worldgen/overworld/manganese_vein.json
  overrides/config/gregtech/worldgen/overworld/medium_oil_sphere.json
  overrides/config/gregtech/worldgen/overworld/molybdenum_vein.json
  overrides/config/gregtech/worldgen/overworld/monazite_vein.json
  overrides/config/gregtech/worldgen/overworld/nickel_vein.json
  overrides/config/gregtech/worldgen/overworld/oilsands_vein.json
  overrides/config/gregtech/worldgen/overworld/olivine_vein.json
  overrides/config/gregtech/worldgen/overworld/pitchblende_vein.json
  overrides/config/gregtech/worldgen/overworld/platinum_vein.json
  overrides/config/gregtech/worldgen/overworld/quartz_vein.json
  overrides/config/gregtech/worldgen/overworld/redstone_vein.json
  overrides/config/gregtech/worldgen/overworld/salts_vein.json
  overrides/config/gregtech/worldgen/overworld/sapphire_vein.json
  overrides/config/gregtech/worldgen/overworld/soapstone_vein.json
  overrides/config/gregtech/worldgen/overworld/tetrahedrite_vein.json
  overrides/config/gregtech/worldgen/overworld/tin_vein.json
  overrides/config/gregtech/worldgen/overworld/tungstate_vein.json
  overrides/config/gregtech/worldgen/overworld/zinc_vein.json
Labels: enhancement

#386 Fix Light Gray spraycan recipe
  overrides/scripts/Earlygame.zs
Labels: enhancement

#385 Fix recipe conflict in #350
  overrides/scripts/Midgame.zs
Labels: bug

#383 Add unique colors to every ore deposite in Scannable
  overrides/config/scannable.cfg
Labels: enhancement
