Repository Nomifactory/Nomifactory, pull requests merged in 2020-05, with the labels that each got.

#460 Add questbook i18n ability
  buildtools/tasks/client/index.js
  buildtools/tasks/server/index.js
  buildtools/tasks/shared/quest_local.js
Labels: enhancement

#481 Add recipes to reset the NBT of Jetpacks
  overrides/scripts/JetpacksAndEnergyStorage.zs
Labels: bug

#489 Bug: Unable to complete quest 'Basic Capacitor Bank' while using a Flux Capacitor. #488
  overrides/config/betterquesting/DefaultQuests.json
Labels: bug, questbook
