Repository Nomifactory/Nomifactory, pull requests merged in 2021-03, with the labels that each got.

#692 Fix English typos and mistakes
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook

#670 Updated launch scripts to print java version
  launchscripts/launch.bat
  launchscripts/launch.sh
Labels: enhancement

#693 add skystone and skystone dust recipes
  overrides/scripts/AE2.zs
Labels: enhancement

#674 Mod updates
  manifest.json
  overrides/config/foamfix.cfg
  overrides/config/ftbutilities.cfg
  overrides/config/packagedauto.cfg
  overrides/config/patchouli.cfg
Labels: dependencies

#647 Added colorized LostCities palette and two profiles using that palette.
  overrides/config/lostcities/colorized.json
  overrides/config/lostcities/general.cfg
  overrides/config/lostcities/icon_colorized.png
  overrides/config/lostcities/profile_coloradventure.cfg
  overrides/config/lostcities/profile_colortalladventure.cfg
  overrides/config/lostcities/profile_colortallsafe.cfg
Labels: enhancement

#704 Remove Duplicate Conductive Iron Cable Recipes
  overrides/scripts/Earlygame.zs
Labels: cleanup

#676 fixed typo with some formatting
  overrides/scripts/Multiblocks.zs
Labels: cleanup

#705 Switch some item renames to lang renames
  overrides/resources/modpack/lang/en_us.lang
  overrides/resources/modpack/lang/ru_ru.lang
  overrides/resources/modpack/lang/zh_cn.lang
  overrides/scripts/Electronics.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/JEICleanup.zs
  overrides/scripts/Microverse.zs
Labels: bug

#715 Update GTCE and SoG
  manifest.json
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/Endgame.zs
  overrides/scripts/zzzFixStuff.zs
Labels: dependencies
