Repository Nomifactory/Nomifactory, pull requests merged in 2021-04, with the labels that each got.

#702 Update LittleTiles & CreativeCore
  manifest.json
  overrides/config/creativecore-client.json
  overrides/config/creativecore.cfg
  overrides/config/littletiles-client.json
  overrides/config/littletiles.cfg
  overrides/config/littletiles.json
Labels: dependencies

#639 Add generation for alternative stone variants (marble/basalt/etc)
  overrides/config/gregtech/worldgen/overworld/basalt_sphere.json
  overrides/config/gregtech/worldgen/overworld/black_granite_sphere.json
  overrides/config/gregtech/worldgen/overworld/marble_sphere.json
  overrides/config/gregtech/worldgen/overworld/red_granite_sphere.json
  overrides/scripts/_oreDict.zs
Labels: enhancement

#721 Suggested fix for Advanced Dislocator NBT
  overrides/config/brandon3055/CustomFusionRecipes.json
Labels: bug

#723 Fix Draconium Ore not being highlighted by scanner
  overrides/config/scannable.cfg
Labels: bug
