Repository Nomifactory/Nomifactory, pull requests merged in 2021-02, with the labels that each got.

#675 Add spark
  manifest.json
Labels: Mod Addition Request, enhancement

#677 Add Reinforced Neon quest book theme
  overrides/config/betterquesting/credits-reinforced-neon.txt
  overrides/config/betterquesting/resources/reinforced-neon/bq_themes.json
  overrides/config/betterquesting/resources/reinforced-neon/textures/gui/reinforced_neon_gui.png
Labels: Mod Addition Request, enhancement

#686 Add Cutting machine recipes for Thermal blocks -> plates
  overrides/scripts/ThermalExpansion.zs
Labels: enhancement

#682 Gregtech update
  manifest.json
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/Midgame.zs
Labels: dependencies, enhancement

#678 remove duplicated lines
  overrides/scripts/_oreDict.zs
Labels: cleanup

#690 Minor quest book changes
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook
