Repository Nomifactory/Nomifactory, pull requests merged in 2021-06, with the labels that each got.

#725 Switch to Dimensional Edibles: Omnifactory Edition
  manifest.json
  overrides/config/DimensionalEdibles.cfg
  overrides/scripts/Alchemy.zs
Labels: Mod Bug, dependencies

#735 Remove recipes for SFT items and add refunds
  overrides/scripts/Earlygame.zs
  overrides/scripts/SimpleFluidTanks.zs
Labels: staggered removal

#753 Replace DWG with DWG: OE
  manifest.json
Labels: Mod Addition Request, enhancement

#752 Add bonus recipes for Ender IO lights
  overrides/scripts/EnderIO.zs
Labels: enhancement
