Repository Nomifactory/Nomifactory, pull requests merged in 2021-12, with the labels that each got.

#821 Changed station light recipe to not conflict with other recipes.
  overrides/scripts/AdvRocketry.zs
Labels: bug

#827 Address confirmed Log4J security vulnerability for Minecraft Servers
  launchscripts/launch.bat
  launchscripts/launch.sh
  manifest.json
  serverfiles/log4j2_112-116.xml
Labels: CI/CD

#835 Don't include client side mods with the server (and vice versa)
  buildtools/tasks/client/index.ts
  buildtools/tasks/server/index.ts
  buildtools/types/modpackManifest.ts
  manifest.json
Labels: enhancement, CI/CD

#585 Add Rubber Trees to Phytogenic Insolator.
  overrides/scripts/ThermalExpansion.zs
Labels: enhancement

#836 Fix molten void crystal color typo
  overrides/scripts/ContentTweaker.zs
Labels: bug

#810 Quest Book Fixes
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook

#833 Fix micro miner naming inconsistencies
  overrides/config/AppliedEnergistics2/items.csv
  overrides/config/betterquesting/DefaultQuests.json
  overrides/resources/contenttweaker/lang/en_us.lang
  overrides/scripts/JetpacksAndEnergyStorage.zs
  overrides/scripts/Multiblocks.zs
Labels: bug, enhancement
