Repository Nomifactory/Nomifactory, pull requests merged in 2021-07, with the labels that each got.

#749 Stage Forestry for Removal
  overrides/config/brandon3055/CSG/Config.json
  overrides/resources/contenttweaker/lang/en_us.lang
  overrides/resources/contenttweaker/models/item/pulsatingdust.json
  overrides/resources/contenttweaker/models/item/pulsatingmesh.json
  overrides/resources/contenttweaker/textures/items/pulsatingdust.png
  overrides/resources/contenttweaker/textures/items/pulsatingdust.png.mcmeta
  overrides/resources/contenttweaker/textures/items/pulsatingmesh.png
  overrides/resources/contenttweaker/textures/items/pulsatingmesh.png.mcmeta
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/Alchemy.zs
  overrides/scripts/BlastFurnace.zs
  overrides/scripts/ContentTweaker.zs
  overrides/scripts/Earlygame.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/EnderIO.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/Forestry.zs
  overrides/scripts/Midgame.zs
  overrides/scripts/SolarFlux.zs
  overrides/scripts/_oreDict.zs
Labels: staggered removal

#665 Quest Book cleanup and updates
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook

#757 Update Gregtech and SoG
  manifest.json
  overrides/config/betterquesting/DefaultQuests.json
  overrides/config/gregtech/dimensions.json
  overrides/config/gtadditions.cfg
  overrides/scripts/Earlygame.zs
  overrides/scripts/Electronics.zs
  overrides/scripts/Multiblocks.zs
Labels: dependencies
