Repository Nomifactory/Nomifactory, pull requests merged in 2022-01, with the labels that each got.

#849 Update AdvancedRocketry for the redux release
  manifest.json
  overrides/config/advRocketry/advancedRocketry.cfg
  overrides/scripts/AdvRocketry.zs
  overrides/scripts/CommonVars.zs
  overrides/scripts/ExtendedCrafting.zs
  overrides/scripts/JetpacksAndEnergyStorage.zs
  overrides/scripts/ThermalExpansion.zs
  overrides/scripts/_oreDict.zs
Labels: enhancement

#840 Buildtools improvements
  buildtools/config.json
  buildtools/globals.ts
  buildtools/gulpfile.ts
  buildtools/tasks/client/index.ts
  buildtools/tasks/client/misc.ts
  buildtools/tasks/deploy/releases.ts
  buildtools/tasks/misc/pruneCache.ts
  buildtools/tasks/misc/zip.ts
  buildtools/tasks/mmc/index.ts
  buildtools/tasks/server/index.ts
  buildtools/tasks/shared/index.ts
  buildtools/tasks/shared/transforms/quest_i18n.ts
  buildtools/util/buildConfig.default.json
  buildtools/util/curseForgeAPI.ts
  buildtools/util/hashes.ts
  buildtools/util/util.ts
  overrides/config/betterquesting/DefaultQuests.json
Labels: CI/CD

#841 Add recipe for the Hyperspace disc
  overrides/scripts/Nuclearcraft.zs
Labels: enhancement

#856 Patch DataFixers to fix issue updating from 1.2.2-redux to dev
  manifest.json
  overrides/bansoukou/gregtech-1.12.2-1.17.1.770/gregtech/api/util/Version.class
Labels: bug

#862 This resolves issue #861 should say oxygen
  overrides/config/betterquesting/DefaultQuests.json
Labels: questbook

#517 Make the void world an AR planet
  overrides/config/advRocketry/advancedRocketry.cfg
  overrides/config/advRocketry/planetDefs.xml
Labels: enhancement

#853 Remove existing Netherrack Macerator recipe
  overrides/scripts/Earlygame.zs
Labels: bug

#863 Restore some missing Neutronium fluid solidifier recipes
  overrides/scripts/_oreDict.zs
Labels: bug
